apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: flask-app
          image: 334645279807.dkr.ecr.us-east-1.amazonaws.com/scan2:140b0d775a53f195a3d64299fcf1ad9a1dac3f1a
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
